site:
  title: Antora Test Project
  start_page: antora-test-project::internal.adoc
   
content:
  sources:
  - url: .
    branches: HEAD, main
    start_path: docs/user-manual
  - url: .
    branches: HEAD, main
    start_path: docs/partner-manual
  - url: https://github.com/polandll/antora-testing
    branches: [main, intman7.1]
    start_path: docs/internal-manual

output:
  dir: ./build/internal

ui:
  bundle:
    url: https://github.com/stargate/antora-ui-stargate/releases/download/v0.5/ui-bundle.zip
  #supplemental_files: ./supplemental-ui
  # override the default _ dir for assets, as Jekyll will delete them
  output_dir: assets

